In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
upload = files.upload()

Saving Data Harga Mobil.csv to Data Harga Mobil.csv


In [ ]:
df = pd.read_csv('/content/Data Harga Mobil.csv', index_col=0)
df

symboling  normalized-losses         make fuel-type aspiration  \
0            3                122  alfa-romero       gas        std   
1            3                122  alfa-romero       gas        std   
2            1                122  alfa-romero       gas        std   
3            2                164         audi       gas        std   
4            2                164         audi       gas        std   
..         ...                ...          ...       ...        ...   
196         -1                 95        volvo       gas        std   
197         -1                 95        volvo       gas      turbo   
198         -1                 95        volvo       gas        std   
199         -1                 95        volvo    diesel      turbo   
200         -1                 95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
196         four        sedan          rwd           front       109.1  ...   
197         four        sedan          rwd           front       109.1  ...   
198         four        sedan          rwd           front       109.1  ...   
199         four        sedan          rwd           front       109.1  ...   
200         four        sedan          rwd           front       109.1  ...   

     bore  stroke  compression-ratio  horsepower peak-rpm city-mpg  \
0    3.47    2.68                9.0       111.0   5000.0       21   
1    3.47    2.68                9.0       111.0   5000.0       21   
2    2.68    3.47                9.0       154.0   5000.0       19   
3    3.19    3.40               10.0       102.0   5500.0       24   
4    3.19    3.40                8.0       115.0   5500.0       18   
..    ...     ...                ...         ...      ...      ...   
196  3.78    3.15                9.5       114.0   5400.0       23   
197  3.78    3.15                8.7       160.0   5300.0       19   
198  3.58    2.87                8.8       134.0   5500.0       18   
199  3.01    3.40               23.0       106.0   4800.0       26   
200  3.78    3.15                9.5       114.0   5400.0       19   

     highway-mpg    price  city-L/100km  horsepower-binned  
0             27  13495.0     11.190476             Medium  
1             27  16500.0     11.190476             Medium  
2             26  16500.0     12.368421             Medium  
3             30  13950.0      9.791667             Medium  
4             22  17450.0     13.055556             Medium  
..           ...      ...           ...                ...  
196           28  16845.0     10.217391             Medium  
197           25  19045.0     12.368421               High  
198           23  21485.0     13.055556             Medium  
199           27  22470.0      9.038462             Medium  
200           25  22625.0     12.368421             Medium  

[201 rows x 28 columns]

In [ ]:
df.shape

(201, 28)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr

LinearRegression()

In [ ]:
X = df[['highway-mpg']]
Y = df[['price']]

In [ ]:
lr.fit(X, Y)

LinearRegression()

In [ ]:
yhat = lr.predict(X)
yhat[0:5]

array([[16236.50464347],
       [16236.50464347],
       [17058.23802179],
       [13771.3045085 ],
       [20345.17153508]])

In [ ]:
print('data', X[:1])
print()
print('Prediksi harganya:', lr.predict(X[:1]))

data    highway-mpg
0           27

Prediksi harganya: [[16236.50464347]]


In [ ]:
lr.intercept_

array([38423.30585816])

In [ ]:
#slope
lr.coef_ 

array([[-821.73337832]])

In [ ]:
data_prediksi =[[27]]

print('Harga yang didapat berdasarkan prediksi', lr.predict(data_prediksi))

Harga yang didapat berdasarkan prediksi [[16236.50464347]]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
Z = df[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']]
lr.fit(Z, df['price'])

LinearRegression()

In [ ]:
lr.intercept_

-15806.62462632922

In [ ]:
lr.coef_

array([53.49574423,  4.70770099, 81.53026382, 36.05748882])

In [ ]:
data_prediksi = [[100, 2525, 100, 30]]
print('harga prediksi :', lr.predict(data_prediksi))

harga prediksi : [10664.64585429]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"
